# Generated by Django 4.2.6 on 2023-10-21 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
