# Generated by Django 4.2.6 on 2023-10-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.TextField(default=None)),
            ],
        ),
    ]
