# Generated by Django 4.2.6 on 2023-10-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueVisitor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=255)),
                ("last_visit_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
