# Generated by Django 4.2.6 on 2023-10-21 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_uniquevisitor_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UniqueVisitor",
        ),
    ]
